spring.datasource.url=jdbc:mysql://localhost:3306/kinodb
spring.datasource.username=Kinouser
spring.datasource.password=Amin2200.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect